spring:
  application:
    name: xkcd-fetcher
  jackson:
    default-property-inclusion: non_empty

  threads:
    virtual:
      enabled: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/xkcd
    change-log: classpath:db/changelog/db.changelog-master.xml
    user: xkcd
    password: xkcd
  datasource:
    url: jdbc:postgresql://localhost:5432/xkcd
    username: xkcd
    password: xkcd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      auto-commit: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    open-in-view: false
    properties:
      hibernate:
        connection:
          autocommit: false
  quartz:
    scheduler-name: xkcd-fetcher-scheduler
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 1
xkcd:
  comic-base-url: https://xkcd.com
  image-base-url: https://imgs.xkcd.com
  excluded-comic-numbers:
    - 404
    - 1663
    - 1608
  scheduler:
    initial-delay-in-minutes: 1
    # interval-in-minutes: 1440 # 24 hours
    interval-in-minutes: 1


garage:
  endpoint: http://localhost:3900
  region: garage
  bucket: xkcd-comics
  credentials:
    access-key: GKafa8532bf619be9ec2af2efa
    secret-key: 6d4e259841952985e1f92d01a24f6f45f63578f1c4461a61e4c0228326dd6481

