spring:
  application:
    name: xkcd-fetcher
  jackson:
    default-property-inclusion: non_empty

  threads:
    virtual:
      enabled: true
  liquibase:
    url: jdbc:postgresql://localhost:5432/xkcd
    change-log: classpath:db/changelog/db.changelog-master.xml
    user: xkcd
    password: xkcd
  datasource:
    url: jdbc:postgresql://localhost:5432/xkcd
    username: xkcd
    password: xkcd
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      auto-commit: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    open-in-view: false
    properties:
      hibernate:
        connection:
          autocommit: false
  quartz:
    scheduler-name: xkcd-fetcher-scheduler
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 1
xkcd:
  comic-base-url: https://xkcd.com
  image-base-url: https://imgs.xkcd.com
  excluded-comic-numbers:
    - 404
    - 1663
    - 1608
  scheduler:
    initial-delay-in-minutes: 1
    # interval-in-minutes: 1440 # 24 hours
    interval-in-minutes: 1


garage:
  endpoint: http://localhost:3900
  region: garage
  bucket: xkcd-comics
  credentials:
    access-key: GK7f62badb97e1914dbe5519e4
    secret-key: 46a84b6f65eab83259172c1008676a218280d3392a45f79ecad040feeba5b41d

httpclient:
  max-total: 50
  default-max-per-route: 20
  redirects-enabled: true
  circular-redirects-allowed: false
  max-redirects: 20
  connect-timeout: 5s
  connection-request-timeout: 3s
  response-timeout: 30s